name: pr-conventional-commit
on:
  pull_request:
    types: [opened,edited,synchronize]

jobs:
  validate-commit-message:
    name: validate-pr-title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}