name: pr-general-actions
on:
  pull_request:
    types: [opened,edited,synchronize]

jobs:
  validate-pr-title:
    name: validate-pr-title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security-analysis:
    needs: [validate-pr-title]
    name: security-scan-snyk
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Check vulnerabilities with Snyk
        uses: snyk/actions/gradle-jdk11@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args:
            --all-sub-projects
            --severity-threshold=high

  static-analysis:
    needs: [validate-pr-title]
    name: sca-sonarcloud
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build and analyze
        run: ./gradlew build jacocoTestReport sonarqube --info
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
