name: push-non-master
on:
  push:
    branches-ignore: [master,main]

jobs:
  prettify-code:
    name: prettify-code
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Prettify the Java Code
        uses: lwerner-lshigh/prettier_action_java@v1.1.1
        with:
          branch: ${{ github.head_ref }}
          prettier_options: '--tab-width 4 --use-tabs true --write **/*.java'